theme: "massively"
baseURL: "https://www.ksenia.dev/"
languageCode: "en-us"
title: "Ksenia Burlachenko"
googleAnalytics: UA-135168444-1
uglyurls: true

params.posts:
  foldername: "post"
  pagesize: "6"
  featuredpost: "true"
